"""Write the manuscript's statistics as LaTeX macros, straight from results/stats.json.

Benjamini-Hochberg q-values depend on the size of the tested family, so every row added anywhere in
the study moves every q. Copying them into the paper by hand let four of them go stale in one week.
The manuscript now reads them from the file this script writes, and nothing volatile is typed.

    python tools/export_numbers.py --out ../es606_tex/numbers.tex
"""
import argparse
import json
from pathlib import Path

# macro name -> stats.json row. Names say what the number is, so the .tex stays readable.
ROWS = {
    "qSilenceMG": "musin_g: silence_naive vs chance",
    "qSilenceNT": "nmed_t: silence_naive vs chance",
    "qBlockNH": "nmed_h: within_naive minus cross_repetition",
    "qLosoNH": "nmed_h: loso_song vs chance",
    "qWithinLosoMG": "musin_g: within_naive minus loso",
    "qWithinLosoNT": "nmed_t: within_naive minus loso",
    "qLinListener": "linear, held-out listener minus its control at 30s",
    "qLinSong": "linear, held-out song minus its control at 30s",
    "qDeep": "deep v2, held-out listener minus its control at 30s",
    "qDeepSym": "deep v2, symmetric imposter minus its control at 30s",
    "qBach": "deep v2, Bach minus its control at 10s",
    "qShiftMG": "alignment shift, MUSIN-G vs speech, 0.5-32 Hz",
}


def sci(q: float) -> str:
    """0.00059 -> 5.9\\times10^{-4}; 0.062 -> 0.062. Plain decimals above 0.01 read better."""
    if q >= 0.01:
        return f"{q:.3f}".rstrip("0").rstrip(".") if q < 0.1 else f"{q:.2f}"
    m, e = f"{q:.1e}".split("e")
    return f"{m}\\times10^{{{int(e)}}}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stats", default="results/stats.json")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rows = {r["row"]: r for r in json.loads(Path(args.stats).read_text())}
    tested = sum(1 for r in rows.values() if r.get("q") == r.get("q"))
    lines = ["% GENERATED by eg606/tools/export_numbers.py from results/stats.json -- do not edit.",
             f"% {tested} rows were tested and corrected together.",
             f"\\newcommand{{\\nTested}}{{{tested}}}"]
    missing = []
    for macro, row in ROWS.items():
        r = rows.get(row)
        if r is None or r.get("q") != r.get("q"):
            missing.append(row)
            continue
        lines.append(f"\\newcommand{{\\{macro}}}{{{sci(r['q'])}}}  % {row}")
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {len(ROWS) - len(missing)} macros to {args.out} ({tested} tested rows)")
    for m in missing:
        print("  MISSING:", m)
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
